[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.12.65"

[[constraint]]
  branch = "master"
  name = "github.com/grafana/grafana_plugin_model"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"
